# Generated by Django 5.1 on 2025-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_friendphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Rasm nomi')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Rasm')),
                ('description', models.TextField(help_text='Uzunroq izoh yozing', verbose_name='Izoh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
